format = """
$os\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$line_break\
$character"""

add_newline = true

[os]
style = 'fg:blue'
format = '[$symbol ]($style)'
disabled = false

[os.symbols]
Arch = "󰣇 "
Manjaro = " "
NixOS = " "


[directory]
style = 'bold fg:blue'
format = '[$path]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = true

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[git_branch]
style = 'fg:green'
symbol = ' '
format = ' [$symbol$branch ]($style)'

[git_status]
style = 'fg:yellow'
format = '([$all_status$ahead_behind]($style) )'

[fill]
symbol = ' '

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'
