format = """
$directory
$character
"""

right_format = """
$git_branch
$git_state
$git_status
$nodejs
$python
$php
$docker_context
$cmd_duration
$status
"""

add_newline = true

[directory]
style = "bold cyan"
read_only = "ğŸ”’"
truncation_length = 10
truncate_to_repo = true

[character]
success_symbol = "[âœ](green)"
error_symbol = "[âœ—](red)"

[git_branch]
format = " [î‚  $branch]($style)"
style = "purple"

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "red"

[nodejs]
format = " [â¬¢ $version]($style)"
style = "green"
disabled = false

[python]
format = " [ğŸ $version]($style)"
style = "yellow"
disabled = false

[php]
format = " [ğŸ˜ $version]($style)"
style = "magenta"
disabled = false

[docker_context]
format = " [ğŸ³ $context]($style)"
style = "blue"
disabled = false

[cmd_duration]
format = " [â± $duration]($style)"
style = "bold yellow"
min_time = 2000

[status]
format = " [âœ— $status]($style)"
style = "bold red"
disabled = false

